### ISSUE TITLE
这段代码，arguments[0]为null，会直接报错

### ISSUE THREAD

**Issue by fenglanzhan** [sensorsdata/sa-sdk-miniprogram#11]
`function click_proxy(option, method) {
  var oldFunc = option[method];

  option[method] = function() {
    var prop = {},
      type = '';

    if (typeof arguments[0] === 'object') {
      var target = arguments[0].currentTarget || {};
      var dataset = target.dataset || {};
      type = arguments[0]['type'];
      prop['$url_path'] = _.getCurrentPath();
      prop['$element_id'] = target.id;
      prop['$element_type'] = dataset['type'];
      prop['$element_content'] = dataset['content'];
      prop['$element_name'] = dataset['name'];
    }
    if (type && _.isClick(type)) {
      sa.track('$MPClick', prop);
    }
    return oldFunc && oldFunc.apply(this, arguments);
  }
};
`

**Comment by com-xubo** [comment]
好的，已经反馈给研发同学，下版会修复。感谢🙏

**Comment by com-xubo** [comment]
这个问题在 1.13.20 版已经修复
