### ISSUE TITLE
mpvue中怎么获取函数名

### ISSUE THREAD

**Issue by controling** [sensorsdata/sa-sdk-miniprogram#12]
在mpvue生成的wxml中，所有事件都被handleProxy的函数接管， 在点击拦截的处理函数中，只能获取到 handleProxy，要怎么获取调用的真正的函数名
![image](https://user-images.githubusercontent.com/20918012/79814651-65e24880-83b1-11ea-9eb2-9f82bb2bf696.png)

**Comment by LeeDou** [comment]
目前神策 SDK 中埋点时并不会传方法名这一参数，可以通过 data-content、data-type 标识这个点击元素的相关属性，完成标识。
如何获取真正的函数名需要进一步去了解 mpvue 的实现原理才能确定是否能获取到真正的函数名。
