### ISSUE TITLE
在QQ小程序生产环境中出现distinct_id丢失问题

### ISSUE THREAD

**Issue by disflyer** [sensorsdata/sa-sdk-miniprogram#14]
![image](https://user-images.githubusercontent.com/22723892/87576707-5a7a9100-c704-11ea-9de5-ceea9a3b906d.png)

问题描述：期望每个埋点的distinct_id都为login id。但生产环境刚进入小程序的几个埋点出现distinct_id丢失的情况,约20%用户会出现如上图的异常数据。

出现频率：偶现

备注：生产环境出现，开发环境没有复现。

代码片段：
``` javascript
      sa.login(my._id)
      sa.registerApp({
        platform: 'qq',
      })
      sa.init()
```

**Comment by com-xubo** [comment]
你好，这个问题可以在微信或者企业微信群中沟通一下
