### ISSUE TITLE
小程序埋点超时

### ISSUE THREAD

**Issue by lvweb** [sensorsdata/sa-sdk-miniprogram#16]
1. 在taro小程序中，按照神策文档添加的前端埋点
2. 线上环境，每天有**几百**条埋点的超时数据报警，神策sql查询有生产数据
3. 神策sql查”进入页面“的数据 比 我们统计的在此页面产生"购买付费"行为的**量少**
4. 小程序埋点是否有限制或者其他要求
5. 神策服务地址是否有更稳定可靠的地址

烦请解答下疑问

**Comment by riyue** [comment]
有统计超时的数据占总数据的百分比吗。量极小的话，不可避免，估计是网络不好导致的超时。量大的话，就是有异常了，可以在微信群众沟通，我们会排查具体是哪里的问题。
