### ISSUE TITLE
[bug] v1.14.1 App 的去除 mp_proxy 改造丢失了 autoTrackIsFirst 的规则

### ISSUE THREAD

**Issue by malei0311** [sensorsdata/sa-sdk-miniprogram#18]
1. 默认 autoTrackIsFirst 为 false, 神策的逻辑在生命周期之后执行
2. 去除 mp_proxy, 改为 wx.onAppShow 之后，丢失了优先级策略

例：在默认情况下，如果想给 某个生命周期添加额外的参数

```
sa.para.autoTrack[hook] = { customField: 'bar' }
```

这样改造后导致，wx.onAppShow 的逻辑优先执行，才去执行 App 中的生命周期函数，造成次序不可控

**Comment by riyue** [comment]
目前我们测试，在新方案中，sa.para.autoTrack[hook] = { customField: 'bar' } 这个自定义参数是可以使用的。没太看懂你说的是什么意思。方便留个微信或者邮箱吗，深入了解下您的问题

**Comment by malei0311** [comment]
> 目前我们测试，在新方案中，sa.para.autoTrack[hook] = { customField: 'bar' } 这个自定义参数是可以使用的。没太看懂你说的是什么意思。方便留个微信或者邮箱吗，深入了解下您的问题

设置在全局当然没问题，如果是动态设置，根据启动参数，如下：（顺序是不能保证的）

```
App({
  onShow(options) {
    // 复现步骤：点击右上角分享，然后返回
    // 会出现先执行 onAppShow 的回调，再执行次数的情况，也就是说此处的设置是没有办法写入到打点数据中的
    this.sensors.para.autoTrack['appShow'] = {
      foo: 'bar',
      ...pick(options.query)
    }
  }
})
```

**Comment by riyue** [comment]
> > 目前我们测试，在新方案中，sa.para.autoTrack[hook] = { customField: 'bar' } 这个自定义参数是可以使用的。没太看懂你说的是什么意思。方便留个微信或者邮箱吗，深入了解下您的问题
> 
> 设置在全局当然没问题，如果是动态设置，根据启动参数，如下：（顺序是不能保证的）
> 
> ```
> App({
>   onShow(options) {
>     // 复现步骤：点击右上角分享，然后返回
>     // 会出现先执行 onAppShow 的回调，再执行次数的情况，也就是说此处的设置是没有办法写入到打点数据中的
>     this.sensors.para.autoTrack['appShow'] = {
>       foo: 'bar',
>       ...pick(options.query)
>     }
>   }
> })
> ```

感谢反馈，我们又测了下，onLaunch和page的show没问题，但是app的onshow确实在新版本有问题。我们现在会暂时把新方案下掉。等出了兼容的解决方案，再更新。
