### ISSUE TITLE
有冲突

### ISSUE THREAD

**Issue by lsgMimi** [sensorsdata/sa-sdk-miniprogram#2]
你们目前的实现方案与小程序使用插件的时候有冲突。
![image](https://user-images.githubusercontent.com/8121777/43697706-847ff334-9978-11e8-83b3-2a107fa74b5f.png)

**Comment by riyue** [comment]
目前修改App和Page的方案是各统计sdk的主流方案，这样的话，可以减少客户的埋点工作量。如果不修改App和Page，所有的埋点都需要客户手动去写，非常麻烦。
针对这个冲突的问题，我们现在也会多加一个不修改的方案。不过，这个方案如上面所说，会导致埋点工作量很大。
