### ISSUE TITLE
SDK中上报方法应设置默认contentType

### ISSUE THREAD

**Issue by csorz** [sensorsdata/sa-sdk-miniprogram#20]
SDK中请求参数
![image](https://user-images.githubusercontent.com/14226595/127085538-4e1c3fe9-9a3d-48ff-9dd2-3adb614cb88a.png)
发送的请求
![image](https://user-images.githubusercontent.com/14226595/127086428-4a2aac37-96c9-4b11-8698-2d121550bb50.png)
服务端会报错，数据类型有问题。

小程序默认**content-type: application/json**，sdk中需要设置为**content-type: text/plain**

**Comment by fengandyun** [comment]
方便留一个联系方式，我和你这边确认下 issue 吗

**Comment by fengandyun** [comment]
小程序 SDK 默认发送时，是使用的 content-type: application/json，该类型与神策分析的服务端是相匹配的，可以正常发送及接收数据，您这边是否是自建的后端接收数据，未设置好类型导致的报错，若是的话，1 可以修改后端配置，2 自己直接修改 SDK 的源码，来满足你自己环境的需求

**Comment by csorz** [comment]
已按方案1修改。已解决
