### ISSUE TITLE
导入 sensorsdata.min.js 文件时报错，有一个 let 未编译成 var

### ISSUE THREAD

**Issue by csorz** [sensorsdata/sa-sdk-miniprogram#21]
见红框处

![image](https://user-images.githubusercontent.com/14226595/132480891-26bf19c5-d4d9-4d81-9cfb-d4ec889257c9.png)

**Comment by com-xubo** [comment]
收到，感谢反馈，我们这边会尽快修复

**Comment by com-xubo** [comment]
你好，你这边方便提供一个复现 demo ,描述一下复现步骤吗？

**Comment by com-xubo** [comment]
该问题在 1.14.22 版本中已修复。
