### ISSUE TITLE
微信小程序sdk如何设置post方式发送数据

### ISSUE THREAD

**Issue by wadekun** [sensorsdata/sa-sdk-miniprogram#22]
如题。web js sdk看到有send_type可以设置post方式发送数据，但是微信小程序sdk官方api文档没看到有相关设置。

**Comment by suguoyao** [comment]
setPara()时，`batch_send:`设置为true就是post请求，否则为get请求

**Comment by riyue** [comment]
> setPara()时，`batch_send:`设置为true就是post请求，否则为get请求

楼上正解
