### ISSUE TITLE
源码中有wx.getLocation 导致审核不通过

### ISSUE THREAD

**Issue by eat-happy** [sensorsdata/sa-sdk-miniprogram#24]
<img width="1219" alt="wecom-temp-7f2bd0ceba7771e22845ab03661fe826" src="https://user-images.githubusercontent.com/34129948/165930044-e63a426b-6aff-406e-b2a1-a72f776127cf.png">

https://developers.weixin.qq.com/community/develop/doc/000e8ccb5ac498318cbd26c495bc01

**Comment by eat-happy** [comment]
小程序类目不符，不能申请该权限

**Comment by Miot** [comment]
用最新版本的sdk
