### ISSUE TITLE
在小程序中使用es6的import方式加载出现以下问题

### ISSUE THREAD

**Issue by chenzuo** [sensorsdata/sa-sdk-miniprogram#31]
找不到模块“/wechat/plugin/exposure/index.esm”或其相应的类型声明。ts(2307)
找不到模块“/wechat/plugin/exposure/index.esm”或其相应的类型声明。ts(2307)
![image](https://user-images.githubusercontent.com/10744915/234448258-8628cf2d-4c91-4729-99dc-c07f92de56b1.png)

**Comment by chenzuo** [comment]
@riyue @lixiang9 这个可以指导我处理一下吗

**Comment by wangzhigang** [comment]
增加 sensorsdata.d.ts 声明文件
