### ISSUE TITLE
小程序启动次数和微信WE分析访问次数对不上。

### ISSUE THREAD

**Issue by ZhouChong1994** [sensorsdata/sa-sdk-miniprogram#35]
小程序启动次数和微信WE分析访问次数对不上。
是否是统计口径上存在差异？
为什么神策统计不直接在onLaunch里采集启动事件，而是在onAppShow里首次上报，这里面是有什么用意吗？

**Comment by wangzhigang** [comment]
1、统计口径有差异。
2、onLaunch 最开始有一些参数获取不到
