### ISSUE TITLE
能否使用 `"miniprogram": "dist",`  替换 main ? 这样能在小程序 npm 中使用

### ISSUE THREAD

**Issue by zhoujinfu** [sensorsdata/sa-sdk-miniprogram#36]
https://github.com/sensorsdata/sa-sdk-miniprogram/blob/ee2a3afff164ab0b4b9c7f4fe99fbf0a49f028e1/package.json#LL5C17-L5C17

**Comment by zhoujinfu** [comment]
Maybe use mini-program npm take the SDK into `package.json` with SCM is a more graceful way in FE engineering.

**Comment by riyue** [comment]
> Maybe use mini-program npm take the SDK into `package.json` with SCM is a more graceful way in FE engineering.

I didn't understand。can you translate it to chinese，and  be more specific。

**Comment by zhoujinfu** [comment]
@riyue 
![image](https://github.com/sensorsdata/sa-sdk-miniprogram/assets/15223662/f373f7a5-8a77-4e14-9259-62717cb89035)

小程序npm 支持 package.json field `miniprogram` 申明 package 产物位置，不然原生小程序 project 无法导入 sdk

**Comment by zhoujinfu** [comment]
或者 `dist/wechat` -> `miniprogram_dist`

**Comment by riyue** [comment]
> 或者 `dist/wechat` -> `miniprogram_dist`

OK，已添加 miniprogram 字段，下个版本会加上。感谢🙏。
