### ISSUE TITLE
package.json的main配置是不是有点问题

### ISSUE THREAD

**Issue by bugszhou** [sensorsdata/sa-sdk-miniprogram#37]
![image](https://github.com/sensorsdata/sa-sdk-miniprogram/assets/46883603/0ecf877e-4eba-4bbf-a8f1-93a40db32571)

为什么路径是【 / 】开头的，

企业级应用能不能走点心

**Comment by lxdonge** [comment]
来信收到。thanks.

**Comment by riyue** [comment]
感谢提醒，下个版本就更新
