### ISSUE TITLE
微信小程序使用registerProperties.hookRegister时hook不到$SignUp事件

### ISSUE THREAD

**Issue by yxyyuanxy** [sensorsdata/sa-sdk-miniprogram#41]
微信小程序使用registerProperties.hookRegister时hook不到$SignUp事件，代码如下：

`registerProperties.hookRegister(function ({event, properties, data}) {
    prop = {project: 'test'}
    return prop;
})`

使用的微信小程序神策sdk 版本： $lib_version: "1.18.4"；

请问这是为什么？ 我该如何解决这个问题？我希望为所有的事件增加一个特定属性，包括$SignUp事件。

**Comment by riyue** [comment]
用 registerPropertyPlugin
