### ISSUE TITLE
sensors中的logout方法不存在

### ISSUE THREAD

**Issue by yellowChao** [sensorsdata/sa-sdk-miniprogram#9]
![image](https://user-images.githubusercontent.com/6483149/70411424-2ca5dd80-1a8d-11ea-9631-4e319e32f5ac.png)
 为什么sensors中的logout方法不存在呢？

**Comment by com-xubo** [comment]
考虑这个方法并不建议客户使用，在微信小程序中就没有提供 logout方法。你们那边是有什么需求需要用到这个方法吗？我可以跟研发同学反馈一下 @yellowChao
